wandb_version: 1

LR:
  desc: null
  value: 0.0005
activation:
  desc: null
  value: SwiGLU
aux_loss_coef:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 128
capacity_factor:
  desc: null
  value: 2
every_n_switch:
  desc: null
  value: 4
expert_dropout:
  desc: null
  value: 0.3
mlp_dropout:
  desc: null
  value: 0.1
n_experts:
  desc: null
  value: 64
norm_first:
  desc: null
  value: true
optimizer:
  desc: null
  value: adamw
switch_first:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703450108.965444
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 5
      13: darwin-x86_64
