wandb_version: 1

LR:
  value: 0.005
activation:
  value: GEGLU
aux_loss_coef:
  value: 0.01
batch_size:
  value: 64
capacity_factor:
  value: 2
every_n_switch:
  value: 3
expert_dropout:
  value: 0.1
mlp_dropout:
  value: 0.2
n_experts:
  value: 8
norm_first:
  value: true
optimizer:
  value: adamw
switch_first:
  value: true
