wandb_version: 1

LR:
  value: 0.001
activation:
  value: GEGLU
aux_loss_coef:
  value: 0.2
batch_size:
  value: 256
capacity_factor:
  value: 1.5
every_n_switch:
  value: 1
expert_dropout:
  value: 0.3
mlp_dropout:
  value: 0.3
n_experts:
  value: 64
norm_first:
  value: false
optimizer:
  value: adamw
switch_first:
  value: true
