wandb_version: 1

LR:
  desc: null
  value: 0.005
activation:
  desc: null
  value: GEGLU
aux_loss_coef:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 64
capacity_factor:
  desc: null
  value: 2
every_n_switch:
  desc: null
  value: 3
expert_dropout:
  desc: null
  value: 0.1
mlp_dropout:
  desc: null
  value: 0.2
n_experts:
  desc: null
  value: 8
norm_first:
  desc: null
  value: true
optimizer:
  desc: null
  value: adamw
switch_first:
  desc: null
  value: true
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: val_loss
parameters:
  desc: null
  value:
    mlp_dropout:
      values:
      - 0.1
      - 0.15
      - 0.2
      - 0.3
      - 0.4
    expert_dropout:
      values:
      - 0.1
      - 0.15
      - 0.2
      - 0.3
      - 0.4
    LR:
      values:
      - 0.0005
      - 0.001
      - 0.003
      - 0.005
      - 0.01
    batch_size:
      values:
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
    optimizer:
      values:
      - adamw
      - sgd
      - momentum
    activation:
      values:
      - GELU
      - GEGLU
      - SwiGLU
    n_experts:
      values:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
    capacity_factor:
      values:
      - 0.5
      - 0.75
      - 1
      - 1.25
      - 1.5
      - 1.75
      - 2
    aux_loss_coef:
      values:
      - 0.005
      - 0.01
      - 0.05
      - 0.1
      - 0.2
    norm_first:
      values:
      - true
      - false
    switch_first:
      values:
      - true
      - false
    every_n_switch:
      values:
      - 1
      - 2
      - 3
      - 4
early_terminate:
  desc: null
  value:
    type: hyperband
    s: 2
    eta: 3
    max_iter: 27
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703449988.483632
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 5
      13: darwin-x86_64
