wandb_version: 1

LR:
  value: 0.005
activation:
  value: GELU
aux_loss_coef:
  value: 0.1
batch_size:
  value: 16
capacity_factor:
  value: 0.5
every_n_switch:
  value: 2
expert_dropout:
  value: 0.3
mlp_dropout:
  value: 0.3
n_experts:
  value: 64
norm_first:
  value: true
optimizer:
  value: adamw
switch_first:
  value: true
